#!/usr/bin/env python3

import skilstak.colors as c
import time

def plain(message):
    '''Clears the screen & says 'Hello World'.'''
    print(c.clear + c.rc() + message + c.reset)

def multi(message):
    '''Print hello world to the console with each charecter in random colors.'''
    
    try:
        while True:
            print(c.clear + c.multi(message))
    except KeyboardInterrupt:
        exit()

def colored(message):
    '''Prints like nyan.'''
    print(c.clear)
    while True:
        print(c.rc() + message +c.x, end=" ")


if __name__ == '__main__':    
    import sys 


#1
    if len(sys.argv) > 2:
        option = sys.argv[1]
        who = sys.argv[2]


    if len(sys.argv) 






#                                    |
#                                   \_/
#-------->       U MUST WRITE 'helloworld c' FOR DIS TO WORK!!!!   <------------
#
#                               ^
#                               |
#                               |
#                               |
