#!/usr/bin/env python3
if __name__ == '__main__':    
    import helloworld as hello

    name, option = hello.parse_args()
    message = "Hello " + name + "!"

    try:
        if option == "-m":
            hello.print_multi(message)
        elif option == "-c":
            hello.print_colored(message)
        else:
            hello.print_plain(message)
    except KeyboardInterrupt:
        exit(0)
