#!/usr/bin/env python3

import skilstak.colors as c
import time

    print(message)   

def print_foreva(message):
    ''' Prints <message> to the screen forever (without line return)
    
    
    Args:
        message (str): message to print forever
        
        
        '''
    print(message,end=' ')

def multi(message):
    '''Print <message> to the console with each charecter in random colors.
    
    
    Args:
        message (str): message to print
        
        
        '''
    
    while True:
            print(c.clear + c.multi(message))
            time.sleep(0.5)
    
def colored(message):
    '''Prints like nyan.'''
    print(c.clear)
    while True:
        print(c.rc() + message + c.x, end=" ")


if __name__ == '__main__':    
    import sys 

    who = "world"
    option = ""
    message = ""

    if len(sys.argv) > 2:
        option = sys.argv[1]
        who = sys.argv[2]
    elif len(sys.argv) == 2:
        if sys.argv[1].startswith("-"):
                option = sys.argv[1]
        else:
            who = sys.argv[1];
        
    message = "Hello " + who + "!";

    try:
        if option == "-m":
            multi(message)
        elif option == "-c":
            colored(message);
        else:
            plain(message);
    except KeyboardInterrupt:
        ()
