#!/usr/bin/env node

'use strict';

var c = require("skilstak-colors");

var printPlain = function () {
  console.log(c.clear + c.x + "Hello World");
}


var printRed = function () {
  console.log(c.clear + c.x + c.red + "Hello World");
}

var printNyan = function () {
  console.log(c.clear + c.x + c.rc() +  "Hello World");
}

var printMulti = function () {
  console.log(c.clear + c.multi("MULTI") + c.x)
}
