#!/usr/bin/env node

'use strict';

var c = require("skilstak-colors");

var printPlain = function (message) {
  console.log(c.clear + c.x + message);
}

printPlain("Hello World")

var printRed = function (message) {
  console.log(c.clear + c.red + message + c.x);
}

printRed("Hello World")

var printNyan = function (message) {
  console.log(c.clear + c.rc() + message + c.x);
}

printNyan("Hello World")

var printMulti = function (message) {
  console.log(c.clear + c.multi(message) + c.x);
}

printMulti("Hello World")

printPlain();



